 version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the Next.js project..."
      - npm run build
      - npm run export   # For static export (only if using `next export`)

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Preparing for deployment..."

artifacts:
  files:
    - '**/*'
  base-directory: out   # For static export, otherwise use `.next`, `public`, etc.
